/**
 * Seed script: fetches BotC roles from json-on-the-clocktower,
 * maps fields to our DB schema, merges Ukrainian translations,
 * and outputs supabase/seed/roles.sql (upsert-safe).
 *
 * Usage: npx tsx scripts/seed-roles.ts
 */

import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import translations from './role-translations.json'

const SOURCE_URL
  = 'https://raw.githubusercontent.com/chizmw/json-on-the-clocktower/main/data/generated/roles-combined.json'

const OUTPUT_PATH = resolve(import.meta.dirname, '../supabase/seed/roles.sql')

// Map source team names to our DB type values
const TEAM_MAP: Record<string, string> = {
  townsfolk: 'townsfolk',
  outsider: 'outsider',
  minion: 'minion',
  demon: 'demon',
  traveler: 'traveller',
  fabled: 'fabled',
}

// Meta entries to skip
const META_IDS = new Set(['_dawn', '_dusk', '_demon', '_minion'])

interface SourceRole {
  id: string
  name: string
  ability: string
  team: string
  edition: string
  firstNight?: number
  firstNightReminder?: string
  otherNight?: number
  otherNightReminder?: string
  reminders?: string[]
  remote_image?: string
  setup?: boolean
}

interface TranslationEntry {
  name_ua: string
  description_ua?: string
}

const translationsMap = translations as Record<string, TranslationEntry>

function escapeSQL(str: string): string {
  return str.replace(/'/g, '\'\'')
}

async function main() {
  // 1. Fetch JSON
  const res = await fetch(SOURCE_URL)
  if (!res.ok) {
    throw new Error(`Failed to fetch: ${res.status} ${res.statusText}`)
  }

  const data = await res.json() as { character_by_id: Record<string, SourceRole> }
  const characters = data.character_by_id

  // 2. Filter and map
  const roles = Object.values(characters)
    .filter(c => !META_IDS.has(c.id) && c.team !== '_meta' && c.edition !== '_meta')
    .map((c) => {
      const type = TEAM_MAP[c.team]
      if (!type) {
        throw new Error(`Unknown team "${c.team}" for role "${c.id}"`)
      }

      const translation = translationsMap[c.id]

      const meta = {
        firstNight: c.firstNight ?? null,
        firstNightReminder: c.firstNightReminder ?? null,
        otherNight: c.otherNight ?? null,
        otherNightReminder: c.otherNightReminder ?? null,
        setup: c.setup ?? false,
        reminders: c.reminders ?? [],
      }

      return {
        id: c.id,
        name_en: c.name,
        name_ua: translation?.name_ua ?? c.name,
        description_en: c.ability,
        description_ua: translation?.description_ua ?? c.ability,
        type,
        edition: c.edition,
        image_url: c.remote_image ?? null,
        meta,
      }
    })
    .sort((a, b) => a.id.localeCompare(b.id))

  // 3. Generate SQL
  const sqlLines = [
    '-- Auto-generated by scripts/seed-roles.ts',
    `-- Source: ${SOURCE_URL}`,
    `-- Generated: ${new Date().toISOString()}`,
    `-- Total roles: ${roles.length}`,
    '',
    'INSERT INTO roles (id, name_en, name_ua, description_en, description_ua, type, edition, image_url, meta)',
    'VALUES',
  ]

  const valueLines = roles.map((r, i) => {
    const imageUrl = r.image_url ? `'${escapeSQL(r.image_url)}'` : 'NULL'
    const comma = i < roles.length - 1 ? ',' : ''

    return `  ('${escapeSQL(r.id)}', '${escapeSQL(r.name_en)}', '${escapeSQL(r.name_ua)}', '${escapeSQL(r.description_en)}', '${escapeSQL(r.description_ua)}', '${r.type}', '${r.edition}', ${imageUrl}, '${JSON.stringify(r.meta).replace(/'/g, '\'\'')}')${comma}`
  })

  sqlLines.push(...valueLines)
  sqlLines.push('ON CONFLICT (id) DO UPDATE SET')
  sqlLines.push('  name_en = EXCLUDED.name_en,')
  sqlLines.push('  name_ua = EXCLUDED.name_ua,')
  sqlLines.push('  description_en = EXCLUDED.description_en,')
  sqlLines.push('  description_ua = EXCLUDED.description_ua,')
  sqlLines.push('  type = EXCLUDED.type,')
  sqlLines.push('  edition = EXCLUDED.edition,')
  sqlLines.push('  image_url = EXCLUDED.image_url,')
  sqlLines.push('  meta = EXCLUDED.meta;')
  sqlLines.push('')

  const sql = sqlLines.join('\n')

  // 4. Write output
  writeFileSync(OUTPUT_PATH, sql, 'utf-8')

  // eslint-disable-next-line no-console
  console.log(`Generated ${OUTPUT_PATH}`)
  // eslint-disable-next-line no-console
  console.log(`Total roles: ${roles.length}`)
  // eslint-disable-next-line no-console
  console.log(`With UA translations: ${roles.filter(r => r.name_ua !== r.name_en).length}`)
}

main().catch((err) => {
  console.error('Seed failed:', err)
  process.exit(1)
})
